title: Emergency Gate Repair
baseURL: /
params:
  layout_style: grid
  palette: blue
  header:
    title: Emergency Gate Repair
    logo_img: /images/emergency-gate-repair.png
    has_nav: true
  footer:
    content: Emergency Gate repair; All rights reserved.
    links:
      - text: Made with Stackbit
        url: https://www.stackbit.com
        new_window: true
    has_social: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
